"use client";

import { useEffect, useState } from "react";
import { cn } from "@/lib/utils";

type Heading = { id: string; text: string; level: 2 | 3 };

/*
 * Side TOC for case studies. Scans the article DOM for h2/h3 with ids
 * (auto-generated by rehype-slug), renders them as a sticky list, and
 * tracks the current section via IntersectionObserver. Hidden on mobile
 * — the editorial reading mode there benefits more from a clean column
 * than from a sidebar.
 */
export function CaseStudyTOC({ label }: { label: string }) {
  const [headings, setHeadings] = useState<Heading[]>([]);
  const [active, setActive] = useState<string>("");

  useEffect(() => {
    const article = document.querySelector("article");
    if (!article) return;
    const els = article.querySelectorAll<HTMLHeadingElement>(
      "h2[id], h3[id]",
    );
    const items: Heading[] = Array.from(els).map((el) => ({
      id: el.id,
      text: el.textContent ?? "",
      level: el.tagName === "H2" ? 2 : 3,
    }));
    setHeadings(items);

    if (items.length === 0) return;

    // rootMargin: heading is "active" when it crosses 80px below the top
    // and before it leaves the upper 30% of the viewport. Picks the first
    // heading that's currently in that band.
    const observer = new IntersectionObserver(
      (entries) => {
        const visible = entries
          .filter((e) => e.isIntersecting)
          .sort(
            (a, b) =>
              a.target.getBoundingClientRect().top -
              b.target.getBoundingClientRect().top,
          );
        if (visible[0]) setActive(visible[0].target.id);
      },
      { rootMargin: "-80px 0px -70% 0px" },
    );

    els.forEach((el) => observer.observe(el));
    return () => observer.disconnect();
  }, []);

  if (headings.length === 0) return null;

  return (
    <nav aria-label={label}>
      <p className="mb-3 font-mono text-[10px] uppercase tracking-[0.2em] text-fg-subtle">
        {label}
      </p>
      <ul className="space-y-1 border-l border-border-subtle">
        {headings.map((h) => {
          const isActive = active === h.id;
          return (
            <li key={h.id}>
              <a
                href={`#${h.id}`}
                className={cn(
                  "-ml-px block border-l-2 py-1 pl-4 text-sm transition-colors",
                  h.level === 3 && "pl-7 text-xs",
                  isActive
                    ? "border-accent text-accent"
                    : "border-transparent text-fg-muted hover:text-fg",
                )}
              >
                {h.text}
              </a>
            </li>
          );
        })}
      </ul>
    </nav>
  );
}
